name: get-classrooms
on: [push]
  # schedule:
  #   - cron: '30 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: get-classrooms
        uses: maku693/action-puppeteer-script@v0
        with:
          script: const page=await browser.newPage();await page.goto('https://www.jiritsu-red.jp/contact/');const list_pref=await page.$$eval("select#schoolprefecture > optgroup > option",options=>options.map(option=>option.textContent));list_pref.shift();let master={};let master_flat=[];for(i=0;i<list_pref.length;i++){const cityOptionNodes=Array.from(document.querySelectorAll("select#schoolcity > option"));cityOptionNodes.shift();master[list_pref[i]]=cityOptionNodes.map(option=>option.text);for(j=0;j<master[list_pref[i]].length;j++){const classroomOptionNodes=Array.from(document.querySelectorAll("select#classroom > option"));classroomOptionNodes.shift();master[list_pref[i]][master[list_pref[i]][j]]=classroomOptionNodes.map(option=>{master_flat.push({pref:list_pref[i],city:master[list_pref[i]][j],id:option.value,name:option.text});return{id:option.value,name:option.text}})}} return master_flat
      - run: echo '${{ steps.get-classrooms.outputs.result }}'
      - run: echo 'var prefOptions = ${{ steps.get-classrooms.outputs.result }}' > classrooms.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
