name: get-classrooms
on:
  schedule:
    - cron: '0 7-22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: get-classrooms
        uses: maku693/action-puppeteer-script@v0
        with:
          script: const page=await browser.newPage();await page.goto('https://www.jiritsu-red.jp/contact/');const gradeOptionNodes=await page.$$eval("select#gakunen > option",options=>options.map(option=>option.textContent));gradeOptionNodes.shift();const list_pref=await page.$$eval("select#schoolprefecture > optgroup > option",options=>options.map(option=>option.textContent));const master={};const master_flat=[];let cityOptions;let classroomOptions;for(i=0;i<list_pref.length;i++){await page.evaluate((list_pref,i)=>{const selectPrefBox=document.getElementById("schoolprefecture");Array.from(selectPrefBox.options).forEach(e=>{if(e.textContent===list_pref[i]){selectPrefBox.selectedIndex=e.index;selectPrefBox.dispatchEvent(new Event("change",{bubbles:!0}))}})},list_pref,i);cityOptions=await page.$$eval("select#schoolcity > option",options=>options.map(option=>option.textContent));master[list_pref[i]]=cityOptions;const list_city=master[list_pref[i]];for(j=1;j<list_city.length;j++){await page.evaluate((list_city,j)=>{const selectCityBox=document.getElementById("schoolcity");Array.from(selectCityBox.options).forEach(e=>{if(e.textContent===list_city[j]){selectCityBox.selectedIndex=e.index;selectCityBox.dispatchEvent(new Event("change",{bubbles:!0}))}})},list_city,j);classroomOptionNodes=await page.$$eval("select#classroom > option",options=>options.map(option=>new Object({id:option.value,name:option.textContent})));console.log(classroomOptionNodes);master[list_pref[i]][master[list_pref[i]][j]]=classroomOptionNodes.map(option=>{master_flat.push(new Object({pref:list_pref[i],city:master[list_pref[i]][j],id:option.id,name:option.name}));return new Object({id:option.id,name:option.name})})}} return new Object({"grades":gradeOptionNodes,"classrooms":master_flat})
      - run: echo '${{ steps.get-classrooms.outputs.result }}' > sprix.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
