name: get-classrooms
on: [push]
  # schedule:
  #   - cron: '30 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: get-classrooms
        uses: maku693/action-puppeteer-script@v0
        with:
          script: function send_selected_text(doc,selector,val){const tar=doc.querySelector(selector);if(tar){setTimeout(()=>{Array.from(tar.options).forEach(e=>{if(e.textContent===val){tar.selectedIndex=e.index;tar.dispatchEvent(new Event("change",{bubbles:!0}))}})},100)}} function wait_switched_options(doc,selector){new Promise(resolve=>{const tar=doc.querySelector(selector);const formObserver=new MutationObserver(records=>{formObserver.disconnect();resolve()}) formObserver.observe(tar,{childList:!0,subtree:!0})})} function _waitForElement(doc,selector,delay=1000,tries=10){const element=doc.querySelector(selector);if(!window[`__${selector}`]){window[`__${selector}`]=0} function _search(){return new Promise((resolve)=>{window[`__${selector}`]++;setTimeout(resolve,delay)})} if(element===null){if(window[`__${selector}`]>=tries){window[`__${selector}`]=0;return Promise.reject(`__${selector} is not found`)} return _search().then(()=>_waitForElement(doc,selector))}else{return Promise.resolve(element)}}
      - run: echo '${{ steps.get-classrooms.outputs.result }}'
      - run: echo 'var prefOptions = ${{ steps.get-classrooms.outputs.result }}' > classrooms.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
