name: get-classrooms
on: [push]
  # schedule:
  #   - cron: '30 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: get-classrooms
        uses: maku693/action-puppeteer-script@v0
        with:
          script: function send_selected_text(doc,selector,val){const tar=doc.querySelector(selector);if(tar){setTimeout(()=>{Array.from(tar.options).forEach(e=>{if(e.textContent===val){tar.selectedIndex=e.index;tar.dispatchEvent(new Event("change",{bubbles:!0}))}})},100)}} const page=await browser.newPage();await page.goto('https://www.jiritsu-red.jp/contact/');const list_pref=await page.$$eval("select#schoolprefecture > optgroup > option",options=>options.map(option=>option.textContent));list_pref.shift();let cityOptions;for(i=0;i<list_pref.length;i++){await send_selected_text(document,"#schoolprefecture",list_pref[i]);cityOptions=await page.$$eval("select#schoolcity > option",options=>options.map(option=>option.textContent));cityOptions.shift()} return cityOptions
      - run: echo '${{ steps.get-classrooms.outputs.result }}'
      - run: echo 'var classroomOptions = ${{ steps.get-classrooms.outputs.result }}' > classrooms.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
