name: get-classrooms
on: [push]
  # schedule:
  #   - cron: '30 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: get-classrooms
        uses: maku693/action-puppeteer-script@v0
        with:
          script: const page=await browser.newPage();await page.goto('https://www.jiritsu-red.jp/contact/');const list_pref=await page.$$eval("select#schoolprefecture > optgroup > option",options=>options.map(option=>option.textContent));list_pref.shift();let master;let cityOptions;for(i=0;i<list_pref.length;i++){await page.evaluate((list_pref,i)=>{const selectBox=document.getElementById("schoolprefecture");Array.from(selectBox.options).forEach(e=>{if(e.textContent===list_pref[i]){selectBox.dispatchEvent(new Event("change",{bubbles:!0}))}})},list_pref,i);cityOptions=await page.$$eval("select#schoolcity > option",options=>options.map(option=>option.textContent));master[list_pref[i]]=cityOptions.shift()} return master
      - run: echo '${{ steps.get-classrooms.outputs.result }}'
      - run: echo 'var classroomOptions = ${{ steps.get-classrooms.outputs.result }}' > classrooms.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
