name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is a pen"
      - id: get-title
        uses: maku693/action-puppeteer-script@v0
        with:
          script: |
            const page = await browser.newPage();
            await page.goto('https://www.jiritsu-red.jp/contact/');
            const title = await page.$eval('title', el => el.textContent);
            const gradeOptionNodes = await page.evaluate(() =>
              Array.from(document.querySelectorAll("select#gakunen > option"));
            );
            gradeOptionNodes.shift();
            const list_grade = gradeOptionNodes.map(option => option.text);
      
            return list_grade;
      - run: echo '${{ steps.get-title.outputs.result }}'